---
- name: Provision VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
    #  - import_tasks: chapter2/pam_pwquality.yml
    #  - import_tasks: chapter2/user_and_group.yml
    #  - import_tasks: chapter3/authorized_keys.yml
    #  - import_tasks: chapter3/two_factor.yml
    #  - import_tasks: chapter4/web_application.yml
    #  - import_tasks: chapter4/sudoers.yml
    #  - import_tasks: chapter5/firewall.yml
  handlers:
    #  - import_tasks: handlers/restart_ssh.yml
